# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Publish

on:
  push:
    tags: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        uses: ./.github/actions/test
        with:
          os: ubuntu-latest
          python_version: '3.7'

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python and Install Dependency
        uses: ./.github/actions/setup_python_poetry
        with:
          os: ubuntu-latest
          python_version: '3.7'
          poetry_group: 'build'
      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
